name: Build Python Binary with PyInstaller

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile --clean --strip edp_cli.py
          mkdir -p dist
          mv dist/edp_cli dist/edp_cli-ubuntu

      - name: Zip binary
        run: |
          cd dist
          zip edp_cli_binary.zip edp_cli-ubuntu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: edp_cli_binary
          path: dist/edp_cli_binary.zip

      - name: Commit binary to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          mkdir -p binaries/ubuntu-latest
          cp dist/edp_cli-ubuntu binaries/ubuntu-latest/edp_cli
          git add binaries/
          git commit -m "Add edp_cli binary for ubuntu-latest"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
