name: Build Python Binaries with PyInstaller

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install typer[all] pyinstaller

    - name: Build binary
      run: |
        pyinstaller --onefile edp_cli.py --name edp_cli

    - name: Zip binary
      run: |
        cd dist
        zip edp_cli-${{ matrix.os }}.zip edp_cli* || zip edp_cli-${{ matrix.os }}.zip edp_cli.exe

    - name: Upload zipped binary
      uses: actions/upload-artifact@v4
      with:
        name: edp-cli-${{ matrix.os }}
        path: dist/edp_cli-${{ matrix.os }}.zip

    - name: Commit binary to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git pull
        mkdir -p binaries/${{ matrix.os }}
        cp dist/edp_cli* binaries/${{ matrix.os }}/ || cp dist/edp_cli.exe binaries/${{ matrix.os }}/
        git add binaries/
        git commit -m "Add edp_cli binary for ${{ matrix.os }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
